---
title: "bed_coverage_analysis"
author: "Ofer Isakov"
date: "3/25/2022"
output: html_document
---

```{r setup, include=FALSE}
analysis_setup_file<-'./config/analysis_setup/template.analysis_setup.txt'
project_dir<-'/media/SSD/Bioinformatics/Projects/gene_coverage_analysis_2022/'
knitr::opts_knit$set(root.dir=project_dir)
knitr::opts_chunk$set(echo = F)
library(ProjectTemplate)
setwd(project_dir)
load.project()
```

```{r prep_analysis}
# prep output
main_output_prefix<-analysis_setup%>%filter(param=='main_output_folder_prefix')%>%pull(value)
main_output_folder<-glue('./output/{main_output_prefix}.coverage_analysis.{Sys.Date()}')
bed_analysis_output_folder<-glue('{main_output_folder}/bed_analysis')
bam_analysis_output_folder<-glue('{main_output_folder}/bam_analysis')
if (!dir.exists(main_output_folder)){dir.create(main_output_folder)}
if (!dir.exists(bed_analysis_output_folder) & analysis_type%in%c('bed','both')){dir.create(bed_analysis_output_folder)}
if (!dir.exists(bam_analysis_output_folder) & analysis_type%in%c('bam','both')){dir.create(bam_analysis_output_folder)}

# copy analysis setup to the ouput folder
system(glue('cp {analysis_setup_file} {main_output_folder}'))
```

```{r bed_coverage_analysis}

input_beds<-c('HPD_v4'='./data/target_intervals/HPD_v4_target_hg19.txt.bed')

target_region<-'/media/SSD/Bioinformatics/Databases/refseq/refseq_hg19_select_cds_20220307.bed.gz'

metrics<-NULL

for (input_bed_name in names(input_beds)){
  input_bed_path<-input_beds[[input_bed_name]]
  message(glue('Analyzing {input_bed_name}: {input_bed_path}'))
  bed_coverage_output<-run_bedtools_coverage_by_bed(reference_bed = target_region,bed_to_test = input_bed_path,output_folder=main_output_folder,bed_name = input_bed_name)
  #bed_coverage<-read_bed_coverage_file(bed_coverage_output)
  cov_per_transcript<-summarize_coverage_per_transcript(bed_coverage_output,output_path=glue('{main_output_folder}/{input_bed_name}/{input_bed_name}_cov_per_transcript.csv'))
  #bed_per_transcript_summary<-bed_per_transcript_summary%>%bind_rows(data.frame(target=output_name,))
  cov_metrics<-get_target_bed_metrics(cov_per_transcript)
  metrics<-metrics%>%bind_rows(data.frame(target_name=input_bed_name,cov_metrics))
}
metrics

```
